language: scala
jdk: oraclejdk8
env:
  - NODE_VERSION="11.6" GITHUB_DEPLOY_BRANCH="deploy"
before_install:
  - nvm install $NODE_VERSION
  - node --version
script:
  - npm install
  - npm run build_production
deploy:
  provider: script
  script: bash .travis/push.sh
  skip_cleanup: true # don't delete built files
  on:
    branch: master
branches:
  except:
    - $GITHUB_DEPLOY_BRANCH # never run on this branch
