var webpack = require('webpack');

/**
 * Extends Webpack config generated by 'scalajs-bundler'
 * @see https://scalacenter.github.io/scalajs-bundler/cookbook.html#how-to-pass-extra-parameters-to-webpack
 */
module.exports = require('./scalajs.webpack.config');

/**
 * Set webpack mode to production. This will make webpack minify
 * our code using the 'Terser' plugin.
 *
 * Since the '*bundle.js' file will be minified, if you need to
 * check the generated code, check the '*opt.js' file.
 *
 * @see https://webpack.js.org/concepts/mode/
 * @see https://github.com/terser-js/terser
 */
module.exports.mode = "production";

/**
 * Ignore unnecessary modules from the bundled file.
 * Edit this rules if the program ever need more modules.
 *
 * This is achieve by using the 'ContextReplacement' and 'Ignore' plugins.
 *
 * @see https://webpack.js.org/plugins/context-replacement-plugin/#usage
 * @see https://webpack.js.org/plugins/ignore-plugin/#example-of-ignoring-moment-locales
 */
module.exports.plugins = [
  // ignore 'highlight.js' files
  new webpack.ContextReplacementPlugin(
    /highlight\.js\/lib\/languages$/,
    /scala|javascript|html|css|scss|java|python|bash/
  ),
  // ignore 'moment' locale files since we don't use that feature
  new webpack.IgnorePlugin({
    resourceRegExp: /^\.\/locale$/,
    contextRegExp: /moment$/
  }),
  new webpack.BannerPlugin(
    `author: Minh Thai <https://github.com/mt40>, ${new Date(Date.now()).toLocaleDateString()}`
  )
];
